:defense_button: "media/images/defense.png"
:monster_spawner: "media/images/monster_spawner.png"
:defending_city: "media/images/defending_city.png"
:floor: "media/images/grass.png"
:cannon: "media/images/cannon.png"
:archer_tower: "media/images/archer_tower.png"
:wizard_tower: "media/images/wizard_tower.png"
:tesla: "media/images/tesla.png"
:wall: "media/images/wall.png"