:monster_weak_1: "media/images/weak_1.png"
:monster_weak_2: "media/images/weak_2.png"
:monster_quick_1: "media/images/quick_1.png"
:monster_big_hp: "media/images/big_hp.png"
:monster_big_shield: "media/images/big_shield.png"
:monster_big_damage: "media/images/big_damage.png"
:monster_quick_big_hp: "media/images/quick_big_hp.png"
:monster_quick_2: "media/images/quick_2.png"
:monster_big_hp_shield: "media/images/big_hp_shield.png"