0:
  :weak_1: 1
1:
  :weak_1: 1
  :weak_2: 1
2:
  :weak_1: 2
  :weak_2: 1
3:
  :weak_1: 2
  :weak_2: 1
4:
  :weak_1: 3
  :weak_2: 2
5:
  :weak_1: 4
  :weak_2: 2
6:
  :weak_1: 5
  :weak_2: 3
  :quick_1: 2
7:
  :weak_1: 6
  :weak_2: 4
  :quick_1: 1
8:
  :weak_1: 7
  :weak_2: 3
  :quick_1: 2
9:
  :weak_1: 8
  :weak_2: 4
  :quick_1: 3